spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://127.0.0.1:3306/feature_probe?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&rewriteBatchedStatements=TRUE&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    initialization-mode: always
    continue-on-error: true
    hikari:
      minimum-idle: 10
      maximum-pool-size: 50
      idle-timeout: 60000
      max-lifetime: 300000
      connection-timeout: 15000
      connection-test-query: SELECT 1 FROM DUAL
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect
    open-in-view: true
  flyway:
    enabled: true


logging:
  level:
    root: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: info
  config: classpath:logback/logback.xml
  file:
    path: ./logs

app:
  toggle-deadline: 30
  server-data-source: MEMORY # DB
  server-base-urls: http://127.0.0.1:4007 # , split
  get-started-server-url: http://127.0.0.1:4007
  analysis-base-url: http://127.0.0.1:4006
  maximum-dependency-depth: 20
  security:
    jwt:
      keystore-location: keys/keystore.jks
      keystore-password: password
      key-alias: jwtsigning
      private-key-passphrase: password
      exclude-tenant-uri:
        - /internal/**
        - /actuator/health
        - /api/login
        - /api/guestLogin
        - /api/v3/api-docs.yaml
        - /api/application/**
      guest-disabled: true
      guest-default-password: Guest_12345
    validator:
      impl: common
