spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://10.179.79.60:4859/feature_probe?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&rewriteBatchedStatements=TRUE&useSSL=false&serverTimezone=Asia/Shanghai
    username: didi_CUxV
    password: 7HmeTHLIw
    type: com.zaxxer.hikari.HikariDataSource
    initialization-mode: always
    continue-on-error: true
    hikari:
      minimum-idle: 10
      maximum-pool-size: 50
      idle-timeout: 60000
      max-lifetime: 300000
      connection-timeout: 15000
      connection-test-query: SELECT 1 FROM DUAL
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect
    open-in-view: true
  flyway:
    enabled: true


logging:
  level:
    root: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: info
  config: classpath:logback/logback.xml
  file:
#    path: /logs



app:
  toggle-deadline: 30
  server-data-source: MEMORY # DB
  security:
    jwt:
      keystore-location: keys/keystore.jks
      keystore-password: password
      key-alias: jwtsigning
      private-key-passphrase: password
      exclude-tenant-uri:
        - /api/server/**
      guest-disabled: true
      guest-default-password: Guest_12345

