{{- if .Values.databaseSecret.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Values.databaseSecret.namePostfix }}
type: Opaque
data:
  {{- range $key, $value := .Values.databaseSecret.secrets }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end}}
