name: Build Analysis & Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'analysis/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'analysis/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'maven'
        
    - name: Build & Test
      run: mvn -B verify --file ./analysis/pom.xml
      
